# Generated by Django 4.2.4 on 2023-09-05 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='historial_pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=6)),
                ('ejercicio', models.CharField(max_length=40)),
                ('subtotal_sin_des', models.FloatField()),
                ('subtotal_años', models.FloatField()),
                ('impuesto_adicional', models.FloatField()),
                ('recargo', models.FloatField()),
                ('descuento_recargo', models.PositiveSmallIntegerField(default=0)),
                ('multa', models.FloatField()),
                ('descuento_multa', models.PositiveSmallIntegerField(default=0)),
                ('aplica_descuento', models.CharField(max_length=15)),
                ('total', models.FloatField()),
                ('estatus', models.CharField(max_length=15)),
                ('autorizacion', models.CharField(max_length=20, null=True)),
                ('cajero', models.CharField(max_length=20)),
                ('contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.datos_contribuyentes')),
            ],
        ),
    ]
