# Generated by Django 4.2.4 on 2023-12-16 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tabla_derechos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_derecho', models.PositiveSmallIntegerField()),
                ('categoria', models.CharField(max_length=200)),
                ('nombre_derecho', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='pagos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('folio', models.BigIntegerField(default=0)),
                ('ejercicio', models.CharField(max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('impuesto_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('recargo', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('desc_recargo', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('desc_multa', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('estatus_descuento', models.CharField(default='NO SOLICITADO', max_length=15)),
                ('cajero', models.CharField(default='N/A', max_length=20)),
                ('estatus', models.CharField(default='NO PAGADO', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('autorizacion', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.datos_contribuyentes')),
            ],
        ),
    ]
