# Generated by Django 4.2.4 on 2023-12-16 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalle_pago_derecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=200)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.tabla_derechos')),
                ('id_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finanzas.pagos')),
            ],
        ),
    ]
