# Generated by Django 4.2.4 on 2023-10-12 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0001_initial'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_pagos',
            name='aplica_descuento',
            field=models.CharField(default='NO SOLICITADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='historial_pagos',
            name='estatus',
            field=models.CharField(default='NO PAGADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='historial_pagos',
            name='folio',
            field=models.CharField(default='NP', max_length=6),
        ),
        migrations.AlterField(
            model_name='historial_pagos',
            name='multa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='historial_pagos',
            name='recargo',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='historial_pago_predial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('folio', models.BigIntegerField(default=0)),
                ('impuesto_predial', models.FloatField()),
                ('impuesto_adicional', models.FloatField()),
                ('recargo', models.FloatField(default=0)),
                ('multa', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('estatus_descuento', models.CharField(default='NO SOLICITADO', max_length=15)),
                ('cajero', models.CharField(max_length=20)),
                ('estatus', models.CharField(default='NO PAGADO', max_length=20)),
                ('total', models.FloatField()),
                ('autorizacion', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.datos_contribuyentes')),
            ],
        ),
    ]
