# Generated by Django 4.2.4 on 2023-12-16 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_detalle_pago_derecho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalle_pago_derecho',
            old_name='categoria',
            new_name='id_derecho',
        ),
    ]
