# Generated by Django 4.2.4 on 2023-10-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_historial_pagos_aplica_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial_pago_predial',
            name='cajero',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='historial_pago_predial',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
