# Generated by Django 4.2.4 on 2023-12-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_tabla_derechos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla_derechos',
            name='categoria',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tabla_derechos',
            name='nombre_derecho',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tabla_derechos',
            name='id',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
