# Generated by Django 4.2.4 on 2023-12-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_rename_categoria_detalle_pago_derecho_id_derecho'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_pago_derecho',
            name='observaciones',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
