# Generated by Django 4.2.4 on 2023-10-12 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0001_initial'),
        ('finanzas', '0004_delete_historial_pago_predial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pago_predial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('folio', models.BigIntegerField(default=0)),
                ('ejercicio', models.CharField(max_length=4)),
                ('impuesto_predial', models.FloatField(default=0)),
                ('impuesto_adicional', models.FloatField(default=0)),
                ('recargo', models.FloatField(default=0)),
                ('multa', models.FloatField(default=0)),
                ('descuento', models.FloatField(default=0)),
                ('estatus_descuento', models.CharField(default='NO SOLICITADO', max_length=15)),
                ('cajero', models.CharField(default='N/A', max_length=20)),
                ('estatus', models.CharField(default='NO PAGADO', max_length=20)),
                ('total', models.FloatField(default=0)),
                ('autorizacion', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.datos_contribuyentes')),
            ],
        ),
    ]
