# Generated by Django 4.2.4 on 2023-10-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_pago_predial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago_predial',
            name='ejercicio',
            field=models.CharField(max_length=20),
        ),
    ]
