# Generated by Django 4.2.4 on 2023-10-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_alter_pago_predial_ejercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago_predial',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
