# Generated by Django 4.2.3 on 2023-07-29 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contribuyente',
            fields=[
                ('rfc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ap', models.CharField(max_length=50)),
                ('am', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_de_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='datos_generales_predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_catastral', models.CharField(max_length=30)),
                ('contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.contribuyente')),
            ],
            options={
                'unique_together': {('clave_catastral', 'contribuyente')},
            },
        ),
    ]
