# Generated by Django 4.1.7 on 2023-08-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Contribuyentes',
            fields=[
                ('clave_catastral', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rfc', models.CharField(max_length=13)),
                ('tramite', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=25)),
                ('apaterno', models.CharField(max_length=25)),
                ('amaterno', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=7)),
                ('calle', models.CharField(max_length=35)),
                ('num_int', models.CharField(max_length=5)),
                ('num_ext', models.CharField(max_length=5)),
                ('colonia_fraccionamiento', models.CharField(max_length=55)),
                ('localidad', models.CharField(max_length=55)),
                ('codigo_postal', models.CharField(max_length=10)),
            ],
            options={
                'unique_together': {('clave_catastral', 'rfc')},
            },
        ),
        migrations.CreateModel(
            name='Domicilio_inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=35)),
                ('col_fracc', models.CharField(max_length=35)),
                ('num_int', models.CharField(max_length=5)),
                ('num_ext', models.CharField(max_length=5)),
                ('localidad', models.CharField(max_length=35)),
                ('pk_fk_clave_catastral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.datos_contribuyentes')),
            ],
        ),
        migrations.CreateModel(
            name='Datos_inmuebles',
            fields=[
                ('id_inmueble', models.AutoField(primary_key=True, serialize=False)),
                ('pk_estado_fisico_predio', models.CharField(max_length=40)),
                ('tipo_predio', models.CharField(max_length=50)),
                ('tenencia_predio', models.CharField(max_length=50)),
                ('modificacion_física_construccion', models.CharField(max_length=50)),
                ('superficie_predio', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('ciudad_localidad', models.CharField(max_length=50)),
                ('uso_predio', models.CharField(max_length=50)),
                ('fk_clave_catastral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.datos_contribuyentes')),
            ],
        ),
        migrations.CreateModel(
            name='Datos_Construccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techos', models.CharField(max_length=20)),
                ('pisos', models.CharField(max_length=20)),
                ('muros', models.CharField(max_length=20)),
                ('tipo_baños', models.CharField(max_length=20)),
                ('instalacion_electrica', models.CharField(max_length=30)),
                ('puertas_ventanas', models.CharField(max_length=20)),
                ('edad', models.CharField(max_length=4)),
                ('niveles', models.CharField(max_length=20)),
                ('plano_croquis', models.CharField(max_length=2)),
                ('doc_just_prop', models.CharField(max_length=2)),
                ('ult_rec_imp', models.CharField(max_length=2)),
                ('lic_obr_dem', models.CharField(max_length=2)),
                ('fk_clave_catastral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.datos_contribuyentes')),
            ],
        ),
    ]
