# Generated by Django 4.1.7 on 2023-08-10 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0002_datos_contribuyentes_domicilio_inmueble_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='datos_documento_predio',
            fields=[
                ('pk_clave_catastral', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('lugar_expedision', models.CharField(max_length=35)),
                ('td', models.PositiveSmallIntegerField()),
                ('num_documento', models.PositiveSmallIntegerField()),
                ('dia', models.PositiveSmallIntegerField()),
                ('mes', models.PositiveSmallIntegerField()),
                ('año', models.PositiveSmallIntegerField()),
                ('num_notaria', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='datos_inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_fk_clave_catastral', models.CharField(max_length=35)),
                ('tipo', models.CharField(max_length=15)),
                ('bajo_numero', models.PositiveSmallIntegerField()),
                ('tomo', models.PositiveSmallIntegerField()),
                ('dia_i', models.PositiveSmallIntegerField()),
                ('mes_i', models.PositiveSmallIntegerField()),
                ('año_i', models.PositiveSmallIntegerField()),
                ('zona_i', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='datos_predio_ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_clave_catastral', models.CharField(max_length=35)),
                ('tipo_avaluo', models.PositiveSmallIntegerField()),
                ('fraccionamiento', models.PositiveSmallIntegerField()),
                ('traslado_dominio', models.PositiveSmallIntegerField()),
                ('regimen', models.PositiveSmallIntegerField()),
                ('tenencia', models.PositiveSmallIntegerField()),
                ('estado_fisico', models.PositiveSmallIntegerField()),
                ('codigo_uso', models.PositiveSmallIntegerField()),
                ('tipo_posecion', models.PositiveSmallIntegerField()),
                ('num_emision', models.PositiveSmallIntegerField()),
                ('tipo_predio', models.PositiveSmallIntegerField()),
                ('uso_predio', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='demeritos_predios_urbanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_clave_catastral', models.CharField(max_length=35)),
                ('descripcion', models.CharField(max_length=35)),
                ('valor', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='incrementos_esquina_urbanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_clave_catastral', models.CharField(max_length=35)),
                ('tipo', models.CharField(max_length=1)),
                ('valor', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='terrenos_rurales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_fk_clave_catastral', models.CharField(max_length=35)),
                ('tipo_suelo', models.PositiveSmallIntegerField()),
                ('valor_has', models.PositiveSmallIntegerField()),
                ('a', models.PositiveSmallIntegerField()),
                ('c', models.PositiveSmallIntegerField()),
                ('sup_has', models.PositiveSmallIntegerField()),
                ('top', models.CharField(max_length=2)),
                ('vias_c', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='terrenos_rurales_superficietotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pk_fk_clave_catastral', models.CharField(max_length=35)),
                ('sup_t_has', models.PositiveSmallIntegerField()),
                ('a', models.PositiveSmallIntegerField()),
                ('c', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='terrenos_urbanos_suburbanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_clave_catastral', models.CharField(max_length=35)),
                ('valor_m2', models.PositiveSmallIntegerField()),
                ('area', models.PositiveSmallIntegerField()),
                ('c', models.PositiveSmallIntegerField()),
                ('frente', models.PositiveSmallIntegerField()),
                ('profundidad', models.PositiveSmallIntegerField()),
                ('valor', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='valores_catastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_catastral_pk', models.CharField(max_length=35)),
                ('valor_terreno', models.BigIntegerField()),
                ('valor_construccion', models.BigIntegerField()),
                ('valor_catastral', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='historial_pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=6)),
                ('ejercicio', models.CharField(max_length=40)),
                ('subtotal_sin_des', models.FloatField()),
                ('subtotal_años', models.FloatField()),
                ('impuesto_adicional', models.FloatField()),
                ('recargo', models.FloatField()),
                ('multa', models.FloatField()),
                ('aplica_descuento', models.CharField(max_length=15)),
                ('descuento', models.FloatField(null=True)),
                ('total', models.FloatField()),
                ('estatus', models.CharField(max_length=15)),
                ('autorizacion', models.CharField(max_length=20, null=True)),
                ('cajero', models.CharField(max_length=20, null=True)),
                ('contribuyente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.datos_contribuyentes')),
            ],
        ),
        migrations.CreateModel(
            name='ficha_datos_construcciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=1)),
                ('tipo_c', models.PositiveSmallIntegerField()),
                ('est', models.PositiveSmallIntegerField()),
                ('terreno', models.PositiveSmallIntegerField()),
                ('antiguedad', models.PositiveSmallIntegerField()),
                ('area_c', models.PositiveSmallIntegerField()),
                ('fk_clave_catastral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.datos_contribuyentes')),
            ],
        ),
    ]
