# Generated by Django 4.2.4 on 2023-08-21 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catastro', '0003_datos_documento_predio_datos_inscripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Gen_contribuyente',
            fields=[
                ('rfc', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('tipo_persona', models.CharField(max_length=30)),
                ('tipo_identificacion', models.CharField(max_length=30)),
                ('numero_identificacion', models.CharField(max_length=25)),
                ('nombre', models.CharField(max_length=35)),
                ('apaterno', models.CharField(max_length=35)),
                ('amaterno', models.CharField(max_length=35)),
                ('curp', models.CharField(max_length=18)),
                ('finado', models.CharField(max_length=2)),
                ('fecha_nacimiento', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
                ('telefono_movil', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=25)),
                ('observaciones', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Datos_gen_predio',
            fields=[
                ('clave_catastral', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('cuenta_predial', models.CharField(max_length=30)),
                ('denominacion', models.CharField(max_length=25)),
                ('tipo_predio', models.CharField(max_length=30)),
                ('uso_predio', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=30)),
                ('zona_valor', models.CharField(max_length=30)),
                ('cuenta_origen', models.CharField(max_length=30)),
                ('fecha_alta', models.CharField(max_length=10)),
                ('motivo_alta', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='predio_nuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_part', models.CharField(max_length=5)),
                ('fk_clave_catastral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.datos_gen_predio')),
                ('fk_rfc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.datos_gen_contribuyente')),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio_predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_fed', models.CharField(max_length=35)),
                ('municipio', models.CharField(max_length=35)),
                ('localidad', models.CharField(max_length=35)),
                ('col', models.CharField(max_length=35)),
                ('calle', models.CharField(max_length=35)),
                ('num_ext', models.CharField(max_length=5)),
                ('letra_ext', models.CharField(max_length=5)),
                ('num_int', models.CharField(max_length=5)),
                ('letra_int', models.CharField(max_length=5)),
                ('ubic_coordenadas', models.CharField(max_length=35)),
                ('fk_clave_catastral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.datos_gen_predio')),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio_noti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entidad_fed', models.CharField(max_length=35)),
                ('municipio', models.CharField(max_length=35)),
                ('localidad', models.CharField(max_length=35)),
                ('col', models.CharField(max_length=35)),
                ('calle', models.CharField(max_length=35)),
                ('cp', models.CharField(max_length=5)),
                ('num_ext', models.CharField(max_length=5)),
                ('letra_ext', models.CharField(max_length=5)),
                ('num_int', models.CharField(max_length=5)),
                ('letra_int', models.CharField(max_length=5)),
                ('fk_rfc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catastro.datos_gen_contribuyente')),
            ],
        ),
    ]
